// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActhh0Lx4XtbcWzs_9grQENvlkGhdJ8qE',
    appId: '1:87798249003:web:18dec6fc0c7c640aa15c6e',
    messagingSenderId: '87798249003',
    projectId: 'ecommerce-94467',
    authDomain: 'ecommerce-94467.firebaseapp.com',
    storageBucket: 'ecommerce-94467.appspot.com',
    measurementId: 'G-KHJTDVMX6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzrDHGcXdfCQH5gBsTPPJFJJ7I3dpEsM',
    appId: '1:87798249003:android:b5df16279c1d93fea15c6e',
    messagingSenderId: '87798249003',
    projectId: 'ecommerce-94467',
    storageBucket: 'ecommerce-94467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBW_gTUCANycgacc48qw0Zt0jHsV-JaGw',
    appId: '1:87798249003:ios:0fad755e9e07950ba15c6e',
    messagingSenderId: '87798249003',
    projectId: 'ecommerce-94467',
    storageBucket: 'ecommerce-94467.appspot.com',
    iosBundleId: 'com.example.ecommAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBW_gTUCANycgacc48qw0Zt0jHsV-JaGw',
    appId: '1:87798249003:ios:0fad755e9e07950ba15c6e',
    messagingSenderId: '87798249003',
    projectId: 'ecommerce-94467',
    storageBucket: 'ecommerce-94467.appspot.com',
    iosBundleId: 'com.example.ecommAssignment',
  );
}
